#!/bin/bash

KERNEL_DIR=$1
GS_BUCKET=$2

cd $KERNEL_DIR
gsutil cp "gs://$GS_BUCKET/build_config" "$KERNEL_DIR/.config"
make olddefconfig
make -j$(nproc)

# copy image to gcs bucket
# gsutil cp "$BUILDS/$KERNEL_DIR/arch/x86/boot/bzImage" "gs://$GS_BUCKET/bzImage"
